export const ROSIE_SEVERITY_CRITICAL = "CRITICAL";
export const ROSIE_SEVERITY_ERROR = "ERROR";
export const ROSIE_SEVERITY_INFORMATIONAL = "INFORMATIONAL";
export const ROSIE_SEVERITY_WARNING = "WARNING";
