export const DIAGNOSTICS_COLLECTION_NAME = "codiga";
export const GRAPHQL_ENDPOINT = "https://api.codiga.io/graphql";
export const POLLING_INTERVAL_MILLISECONDS = 200;
export const POLLING_DEADLINE_MILLISECONDS = 10000;
export const TIME_BEFORE_STARTING_ANALYSIS_MILLISECONDS = 1500;

export const CODING_ASSISTANT_WAIT_BEFORE_QUERYING_RESULTS_IN_MS = 200;

export const MESSAGE_STARTUP_SHOW_SHORTCUTS = "Shortcut";
export const MESSAGE_STARTUP_SHOW_SNIPPETS = "Snippets";
export const MESSAGE_STARTUP_DO_NOT_SHOW_AGAIN = "Do not show";

export const STATUS_ERROR = "Error";
export const STATUS_DONE = "Done";

export const DIAGNOSTIC_CODE = "codiga";

export const LEARN_MORE_COMMAND = "LearnMore";
export const IGNORE_VIOLATION_COMMAND = "IgnoreViolation";

export const ENGINE_ESLINT_APOLLO_CLIENT_ENABLED =
  "ENGINE_ESLINT_APOLLO_CLIENT_ENABLED=true";
export const ENGINE_ESLINT_GRAPHQL_ENABLED =
  "ENGINE_ESLINT_GRAPHQL_ENABLED=true";
export const ENGINE_ESLINT_EXPRESS_ENABLED =
  "ENGINE_ESLINT_EXPRESS_ENABLED=true";
export const ENGINE_ESLINT_REACT_ENABLED = "ENGINE_ESLINT_REACT_ENABLED=true";
export const ENGINE_ESLINT_JEST_ENABLED = "ENGINE_ESLINT_JEST_ENABLED=true";
export const ENGINE_ESLINT_CHROME_EXTENSION_ENABLED =
  "ENGINE_ESLINT_CHROME_EXTENSION_ENABLED=true";
export const ENGINE_ESLINT_AWS_SDK_ENABLED =
  "ENGINE_ESLINT_AWS_SDK_ENABLED=true";
export const ENGINE_ESLINT_TYPEORM_ENABLED =
  "ENGINE_ESLINT_TYPEORM_ENABLED=true";

export const NODE_PACKAGE_FILE = "package.json";
export const COMPOSER_FILE = "composer.json";
export const REQUIREMENTS_FILE = "requirements.txt";
export const GEMFILE_FILE = "Gemfile";

export const AUTO_COMPLETION_CHARACTER_TRIGGER = ".";
